root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /homepage
        permanent: true

homepage:
    path:  /homepage
    defaults: { _controller: BlogBlogBundle:Default:homepage }

about:
    path:  /about
    defaults: { _controller: BlogBlogBundle:Default:about }

# Blog
blog:
    path: /blog/{author}/{page}
    defaults: { _controller: BlogBlogBundle:Blog:blog }
    requirements:
        page: \d+

blog_show:
    path: /blog/{author}/{id}_{title}
    defaults: { _controller: BlogBlogBundle:Blog:show, id: 0, title: "" }
    requirements:
        id: \d+

blog_create:
    path: /author/blog/create
    defaults: { _controller: BlogBlogBundle:Blog:edit, id: 0 }

blog_edit:
    path: /author/blog/edit/{id}
    defaults: { _controller: BlogBlogBundle:Blog:edit }
    requirements:
        id: \d+

blog_delete:
    path: /author/blog/delete/{id}
    defaults: { _controller: BlogBlogBundle:Blog:delete }
    requirements:
        id: \d+

# Gallery
gallery_display:
    path: /gallery/{id}
    defaults: { _controller: BlogBlogBundle:Gallery:display, id: 0 }
    requirements:
        id: \d+

gallery_create:
    path: /author/gallery/create
    defaults: { _controller: BlogBlogBundle:Gallery:edit, id: 0 }

gallery_edit:
    path: /author/gallery/edit/{id}
    defaults: { _controller: BlogBlogBundle:Gallery:edit }
    requirements:
        id: \d+

gallery_delete:
    path: /author/gallery/delete/{id}
    defaults: { _controller: BlogBlogBundle:Gallery:delete }
    requirements:
        id: \d+
