imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    facebook_app_id: "id_app"
    facebook_app_secret: "secret_key_app"
    google_app_id: "id_app"
    google_app_secret: "secret_key_app"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "MopaBootstrapBundle", "BlogBlogBundle", "FOSCommentBundle", "BernusDesignBundle", "MastioPhotoSwipeBundle" ]
    java: /usr/bin/java
    ruby: /usr/bin/ruby
    filters:
        cssrewrite: ~
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: "\.less$"
        compass:
            sass: /usr/local/bin/compass
            #apply_to: "\.(scss|sass)$"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        closure:
           jar: %kernel.root_dir%/Resources/java/compiler.jar
    assets:
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery-1.11.3.js
            output: js/jquery.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS User Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Blog\UserBundle\Entity\User

# HWIO Auth
hwi_oauth:
    connect:
        account_connector: my_user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_app_id%"
            client_secret:       "%facebook_app_secret%"
            scope:               ""
        google:
            type:                google
            client_id:           "%google_app_id%"
            client_secret:       "%google_app_secret%"
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

# FOS Comment Configuration
fos_comment:
    db_driver: orm
    acl: true
    class:
        model:
            comment: Blog\CommentBundle\Entity\Comment
            thread: Blog\CommentBundle\Entity\Thread
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
    acl_roles:
        comment:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_AUTHOR
        thread:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN

# Mopa Bootstrap Configuration
mopa_bootstrap:
    menu:
        template: BlogBlogBundle:Menu:menu.html.twig
    form:
        show_legend: false
        render_optional_text: false
        checkbox_label: 'label'
    initializr:
        meta:
            title:        "L'Outre-Ça"
            description:  "Blog réunissant Oxylos (anciennement Quasar) et Tarran. Un dessinateur et un poète"
            keywords:     "Oxylos, Quasar, Tarran, BD, poème, forum dessiné, dessin, roman"
            author_name:  "Mastio Guillaume"
            # author_url:   "mailto:gm3122@gmail.com"
        dns_prefetch:
            - '//ajax.googleapis.com'
        # google:
        #     wt: 'xxx'
        #     analytics: 'UA-xxxxxxx-xx'
        # diagnostic_mode: true

# CKEditor
trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    # customConfig: bundles/mastioblog/ckeditor/config.js
    # skin: ''
    # transformers: ['resize_images']
    toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'tools']
    toolbar_groups:
        document: ['Source','Syntaxhighlight']
        editing: ['Bold','Italic','Underline', '-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock']
        linksandimage: ['Link','Unlink', '-', 'Image']
    # filebrowser_upload_url:
    #     url: upload

    # external_plugins:
    #     syntaxhighlight:
    #         path: js/ckeditor/plugins/syntaxhighlight
    filebrowser_image_browse_url:
        route: elfinder
        route_parameters:
             instance: ckeditor

# ElFinder
fm_elfinder:
    instances:
        ckeditor:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
