<?php

namespace Blog\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findMostRecent($nbOfResult)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM MastioBlogBundle:Article a WHERE a.isPublish = true ORDER BY a.date DESC')
            ->setMaxResults($nbOfResult)
            ->getResult();
    }
}
