Blog\UserBundle\Entity\User:
    type: entity
    table: blog_user
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        facebook_id:
            type: string
            length: 255
            nullable: true
        facebook_access_token:
            type: string
            length: 255
            nullable: true
        google_id:
            type: string
            length: 255
            nullable: true
        google_access_token:
            type: string
            length: 255
            nullable: true
    oneToMany:
        articles:
            targetEntity: Blog\BlogBundle\Entity\Article
            mappedBy: author
    lifecycleCallbacks: {  }
